### ISSUE TITLE
REQUEST ERROR? AFTER 1000 LINKS or maybe because a link was double cloaked (shortened twice)

### ISSUE THREAD

**Issue by znatski** [marirs/urlexpand#5]
BRO, I LOVE YOUR CODE, listen, i'm not a programmer, but exactly 8 hours ago I installed RUST for the first time, fast forward, exactly 30 minutes ago I was already using your code expanding 30,000 links, thanks for your work

HOWEVER, I would like to discuss if there are going to be limitation to how many request we can pull in one execute? There was an instance where it went error after the 1,030th request, perhaps because the last request had a link cloaked twice from t.co to bit.ly, but there was a final destination yet to be expanded, do you think this was a limitation to the program or do you think it was the former?

ANYWAY, I will post below my code for unshortening 30,000 links, I'm really new to this GitHub thing and I can't find a way to contact you so here I am, cheers! Hope u reply! See ya

```rust
use std::io::Read;
use std::fs::File;
use std::io::Write;
use urlexpand;

#[tokio::main]
async fn main() {
    let mut file = std::fs::File::open("data.csv").unwrap();
    let mut save_file = File::create("data_new.csv").unwrap();
    let mut contents = String::new();
    file.read_to_string(&mut contents).unwrap();
    println!("{}", contents);

    for url in contents.lines() {
        let x = urlexpand::is_shortened(&url);
        if x {
            match urlexpand::unshorten(&url, None).await {
                Ok(u) => { writeln!(&mut save_file, "{}", u).unwrap(); },
                Err(e) => println!("{}", e),
            }
        } else {
            println!("{} not a short url", url)
        }
    }
}
```

**Comment by marirs** [comment]
Hi @znatski 
Gratitude for your appreciation. Thanks for using urlexpand :)

I must say, you did a great project in installing Rust just 8hrs back and started off expanding tons of links. Your code surely does not look newbie too. It looks certainly professional. Awesome to see people with such sharp minds who are so flexible in quickly adapting to something brand new.
Btw: I Love Rust. Those guys wrote the best programming lang.

For your question, I dont see a limitation.
https://github.com/marirs/urlexpand/blob/main/src/resolvers/mod.rs#L30 - is where the custom redirect policy is written, so as long as the host is not the same, it will keep following the redirects. If its Ok with you, just send me the link for me to check once and I can see if I can tweak my code for scenarios of your kind as well. The Cargo.toml has my email id if you wish to send via email.

Also if you have lots of links - just for bitly etc, you might want to slow down talking to their servers quickly as sometimes they might have a throttle as well. Just thinking out loud.

Thanks again.

**Comment by marirs** [comment]
Have closed this for now. but feel free to write back here if there is anything else.

Thanks
